### ISSUE TITLE
Starting tmux module outside of tmux needs to warn

### ISSUE THREAD

**Issue by garciadrew07** [pnegahdar/venvy#7]
Currently if you start a mux session from venvy outside of tmux a generic error is shown.

**Comment by stcrestrada** [comment]
Will take a look shortly @garciadrew07

**Comment by stcrestrada** [comment]
Hey there, this is another comment.

**Comment by pnegahdar** [comment]
lets be real you dont know what to do with it...

**Comment by pnegahdar** [comment]
hehehe

**Comment by stcrestrada** [comment]
Nah, I figured it out. Thanks. :)

**Comment by pnegahdar** [comment]
Test

**Comment by stcrestrada** [comment]
Please test again. Thanks!

**Comment by stcrestrada** [comment]
jackson is taking over. Thanks!
